Repository jotoho/cpp2-praktikum, pull requests merged in 2022-04, with the labels that each got.

#3 Automatically assign reviewer for repo management & CI
  .github/CODEOWNERS
Labels: documentation, enhancement

#7 Add project URL to code files
  1/main.cpp
  1/stack.cpp
  1/stack.hpp
  2/main.cpp
  2/stack.cpp
  2/stack.hpp
Labels: documentation

#8 Modified Stack to use dynamically alloc memory
  2/stack.cpp
  2/stack.hpp
Labels: enhancement

#10 Implement double linked list as described in on sheet 3
  3/compile.sh
  3/list.cpp
  3/list.hpp
  3/main.cpp
Labels: enhancement
